### ISSUE TITLE
Fails with PERL_USE_UNSAFE_INC=0 and Perl >= 5.26

### ISSUE THREAD

**Issue by andk** [zoffixznet/Mew#5]
Sample fail report: http://www.cpantesters.org/cpan/report/96621818

All reports and their realtion to PERL_USE_UNSAFE_INC: http://analysis.cpantesters.org/reports_by_field?distv=Mew-1.002001;field=env%3APERL_USE_UNSAFE_INC;order=1ta,2ta

**Comment by zoffixznet** [comment]
Thanks. Fixed!
